### ISSUE TITLE
Emails not being sent out for password reset

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#109]
Site (Humanities Commons, MLA Commons, UP Commons, etc.): All
User Account: mzapedowska
Area (CORE, sites, profiles, groups, general): COmanage

**Describe the bug**
When you click the 'Forgot Password' link after selecting Humanities Commons login, no email is sent. Sparkpost does not show any generated event.

**Comment by ericknappe** [comment]
Theory is that, based on the fact that some email servers have stricter checking than others, sunypress.edu is rejecting the email to amanda because the email is from hcommons.org via amazonses.com. We've moved the password reset from amazonses to sparkpost. After testing some password resets in hcdev, we plan to implement this change in prod

**Comment by ericknappe** [comment]
@bjr70 please plan some testing with a few emails - any .edu emails you control that are enrolled in hcdev and a gmail or two.

**Comment by bjr70** [comment]
I've tested it with multiple users. This is working.

**Comment by bjr70** [comment]
Fix works.

**Comment by bjr70** [comment]
This is fixed. Closing.
