### ISSUE TITLE
No member type on newly registered tester - missing badge; can join groups across networks

### ISSUE THREAD

**Issue by adonlon** [MESH-Research/commons#144]
- [x ] Add to an appropriate Epic.

Tester (if different from issue creator): Anne
Site: MLA Commons
URL: mla.hcommons.org
Test Account: HCTester10
Area (CORE, sites, profiles, groups, general): network membership
If issue discovered on dev, does it also exist on prod? 

**Describe the issue**
I registered successfully as HCTester10 via MLA Commons (implying that I have active MLA membership). 

However, I don't have an MLA badge on the profile. 
I am able to join MLA Commons groups. 

But I am also able to join groups on CAA, MSU, and SAH Commons, where according to the tester spreadsheet, I shouldn't have membership. 
On UP Commons, I saw the "Join" buttons but the button never completed its action, just had a circle animation. 

**To Reproduce**
1. Register a test user with society membership and check member type on wp-admin/network/users
2. If none, try to join groups on society commons. (Note that because of the comanage quirk, you don't remain logged in across networks and you have to log in at each.) 
3. Check avatar for society badges. 

**Expected behavior**
The tester should have badges to indicate society/institution membership and the tester should not be able to join groups in networks where they do not have membership. Instead, they should see grayed out boxes. 

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rekmla** [comment]
Seems like multiple issues:

Grouper sync did not happen, the ldap record in registry is incorrect. In fact, hctester10 has no isMemberOf records and should have no access.

Any access currently granted to hctester10 seems "incorrect"

**Comment by mikethicke** [comment]
It seems like hctester10 has the right groups on dev and doesn't exist on prod.

CO Person record on dev: https://registry.hcommons-dev.org/registry/co_people/canvas/124895

When I registered a random account on MLA-dev it was rejected.

I registered Ferdinand Test (hctester40) through MLA-dev, they were registered successfully. They lack badges like hctester10 and can access groups like hctester10. They are an active member of MLA on their CO Person record: https://registry.hcommons-dev.org/registry/co_people/canvas/124902

So is this just a problem of the badges not showing correctly?

**Comment by rekmla** [comment]
No, tester10 did not get synced by grouper. There are no isMemberOf attributes. Here is the ldap:

ssh dev_registry
ldapsearch -LLL -H ldapi:/// -D uid=comanage,ou=system,o=HC,dc=commons,dc=mla,dc=org -x -w XXXX -b ou=people,o=HC,dc=commons,dc=mla,dc=org "(employeeNumber=hctester10)"
dn: employeeNumber=hctester10,ou=people,o=HC,dc=commons,dc=mla,dc=org
sn: Test
cn: Barty Test
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: eduPerson
objectClass: voPerson
objectClass: eduMember
title: Graduate Student, Russian Literature
givenName: Barty
o: University Of Iowa
mail: hctester10@gmail.com
employeeNumber: hctester10
employeeType: member
uid: 100727731664690635055+google.com@commons.mla.org
eduPersonAffiliation: member
voPersonApplicationUID: 10002
voPersonApplicationUID: hctester10
voPersonApplicationUID: hc75396826
voPersonStatus: Active


I went to dev grouper to kick off the sync with these steps:

ssh dev_grouper
cd /opt/grouper/grouper.apiBinary-2.2.2
/opt/grouper/grouper.apiBinary-2.2.2$ sudo -u tomcat6 MEM_MAX=2048m ./bin/gsh.sh -psp -sync hctester10

ldap now looks like this

admin@ip-10-98-11-244:~$ ldapsearch -LLL -H ldapi:/// -D uid=comanage,ou=system,o=HC,dc=commons,dc=mla,dc=org -x -w XXX -b ou=people,o=HC,dc=commons,dc=mla,dc=org "(employeeNumber=hctester10)"
dn: employeeNumber=hctester10,ou=people,o=HC,dc=commons,dc=mla,dc=org
sn: Test
cn: Barty Test
...
isMemberOf: Humanities Commons:HC:members_HC
isMemberOf: Humanities Commons:MLA:members_MLA
isMemberOf: Humanities Commons:members

HOWEVER, that is not enough! the WP record does not have the HC and MLA member types. In PROD, there is a process to run to add member_type whih controls badge. In DEV I usually just delete and enroll again. I'll update this one in dev to show what happens if a user gets fixed.

**Comment by rekmla** [comment]
ubuntu@hcommons-dev:~/utils/migration$ wp --url=hcommons-dev.org eval-file parse_mla_userlist_fix_type.php fix_hctester10.csv

**Comment by rekmla** [comment]
Long term fixes:
remove grouper
enable member type maintenance (multiple values) in wp-admin/network/users

**Comment by adonlon** [comment]
HCTester10 seems to be behaving well! Has MLA badge, can join MLA groups but not groups in other networks. I see the expected logged-in non-member view on UP, SAH, etc.

Account was removed from the Ask UP site, correctly, I think, as it doesnt have UP Commons access. 

However, hctester10 remains a member of the groups joined when there was no member type on the account, on MSU, UP, SAH, CAA. This may be a current problem on prod too (based on expired MLA members no longer with MLA Commons access but remaining in MLA groups).

The spreadsheet indicates this tester should have ARLIS but is not recognized as a member of ARLIS NA Commons. Not sure if that's a concern or not.

**Comment by mikethicke** [comment]
re: removing users from society groups when no longer a member: https://app.zenhub.com/workspace/o/mesh-research/commons/issues/152
