### ISSUE TITLE
Users not picking up title and organizational affiliation during enrollment

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#164]
Site (Humanities Commons, MLA Commons, UP Commons, etc.): MLA Commons
User Account: 

- https://hcommons.org/members/roitartakovsky/ 
- https://registry.hcommons.org/registry/co_people/canvas/126205
- https://hcommons.org/members/cynthiarwallace/ 
- https://registry.hcommons.org/registry/co_people/canvas/126220
- https://hcommons.org/members/rolandvegso/ 
- https://registry.hcommons.org/registry/co_people/canvas/126192

Area (CORE, sites, profiles, groups, general): general

**Describe the bug**

adonlon
9:41 AM
I was taking a look at newly registered members on HC and an awful lot don't have title & affiliation. A number are MLA members. Is it only if they register through MLA Commons that they pick up title and affiliation from the database? I don't know how to tell what enrollment flow they used, but I wonder if it's worth checking on? Looking at newly registered on the MLA Commons member page, only 5 out of 20 have institution listed. (vs. last active, where only one doesn't have affiliation).  Here are some examples where the MLA record has info that didn't show up on the Commons profile: 

**Expected behavior**

When a user registers through MLA (or other societies that provide that data), the enrollment flow should pick up their organization and title and propagate that to their WordPress profile.

**Other Context**
	
mikethicke
9:50 AM
So for the top one, what's missing is Title: Sr Lect and Organization: Tel Aviv U?
Do you know if that is data that propagated to WordPress in the past?

adonlon
9:52 AM
If they enroll through MLA Commons, it definitely has in the past, I'm less certain whether it happens when an MLA member enrolls through HC. And I'm not sure whether these recent ones enrolled through MLA or HC.  
	
kfitz
9:53 AM
Yeah, only folks who register through an enrollment flow that connects to a DB from which we can grab that info have it auto-populated; otherwise they're asked to supply it but I think are not required to do so

I'm not sure why those for whom it is being snagged don't have it appearing tho

eknappe
9:55 AM
Could be a problem with the HTTP variables not getting picked up by the humanities-commons plugin. Might be simplesaml related.

**Comment by adonlon** [comment]
I noticed today on the recommendation widget that a handful of the recent registrations on MLA Commons don't have first name + last name (nor affiliation). Name is required during registration so it seems that something is being dropped somewhere. The names appear on the /members directory but not on the profile page or recommendation widget.

**Comment by bjr70** [comment]
Looks like names aren't coming through again either. 
https://hcommons.org/members/jrintaugu/

**Comment by mikethicke** [comment]
It would be really great if we could reliably reproduce this. 

In particular, I'd like to know how often this happens when a user registers and if it is at all correlated with society membership.

**Comment by bjr70** [comment]
In looking at new users who have just joined this looks like it may be related to society membership. Those who join HC look to have names, those who join through UP don't.

**Comment by adonlon** [comment]
If we're looking at title and affiliation, though, it seems to affect HC-only as well. e.g. https://registry.hcommons.org/registry/co_people/canvas/129879 has title and affiliation entered in comanage but not displayed in WP.

**Comment by bjr70** [comment]
There's such an inconsistency in name, but affiliation never seems to come over.

**Comment by adonlon** [comment]
I was thinking name was a similar enough issue to title/affiliation but maybe it's a separate issue. 

Looking at recent registrations on MLA Commons, most have names. There are 4 of the most recent 30 registrations with no names displaying on profile/recommendation widget (as a reminder the names do display on /members directory, so they're coming over somewhere): 
- https://mla.hcommons.org/members/carmelapanarello/
- https://mla.hcommons.org/members/dgideon/
- https://mla.hcommons.org/members/sarahlucena/
- https://mla.hcommons.org/members/samstephens/
There are also some with affiliation, though many have edited their profile otherwise so it may have been added there. But here's one that seems v likely to come from the MLA database based on the format and if I'm reading the comanage record correctly: https://mla.hcommons.org/members/poulethelen/ https://registry.hcommons.org/registry/co_people/canvas/129413

All of these linked above used the MLA Commons enrollment flow, so that doesn't seem to be the only variable, since some have no name/affiliation and one has both name and affiliation. (And thinking about the most recent 30 registrations, it seems likely there are others that used the MLA Commons enrollment flow and have name but no affiliation, and I imagine at least one might have used the HC enrollment flow (but that's just a guess). And all have picked up society membership, so they had some contact with the society database. The search for the key variable continues, I think.)

**Comment by bjr70** [comment]
Adding https://hcommons.org/members/kshermeyer/. She came in through MLA this morning and has no name or affiliation.

**Comment by mikethicke** [comment]
Can we retest this / check whether newly-generated MLA members have correct name and affiliation?

**Comment by mikethicke** [comment]
This seems to still be happening for some users.

The code in hc-simplesaml seems to be working appropriately. New MLA users are also being correctly provisioned to LDAP as far as I can tell.

Adding some additional logging to try to diagnose the issue: https://github.com/MESH-Research/humanities-commons/commit/f54b5b10d82223e1b1266b63c1f0846849bd6802

**Comment by mikethicke** [comment]
Investigation has not revealed any clear problem with the current system, other than that when users authenticate their data is sometimes not passed to WordPress. I don't see any clear cause of this, and when it does occur the user's profile *should* be updated appropriately the next time they login.

This issue points to a larger issue with the unreliability of our current method of passing user data from COmanage to WordPress. The following project is meant to address that: https://github.com/MESH-Research/commons/issues/584
