### ISSUE TITLE
Fix UI and logic for joining groups

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#209]
The UI and logic for joining (society) groups is broken. Rewrite the UI logic in ```hc-custom/includes/buddypress/bp-groups.php``` to ensure that:

On the groups listing page:

For society members:
- [x] Private groups have a 'Request Access' button
- [x] Public groups have an enabled Join button
- [x] Committees have no join or request button

For non-society members:
- [x] The same UI elements as above appear, but are greyed-out

In the banner for a group:
- [ ] The same UI elements as above appear in the same circumstances

**Comment by adonlon** [comment]
When logged out I see messaging/greyed out buttons that should appear only for a logged-in non-member of a society/institution. They also appear on HC. [Screen Shot 2021-12-08 at 11.55.18 AM.png](https://images.zenhubusercontent.com/61435c13ba17b3e6f56dd4ce/bdcfd1e8-a01d-4e4f-b82c-2dd4c645e61c) The logic is e.g. on /groups and /members. The message on /groups includes a link to "Join [society]" which I think was initially set to go to a society page to join the society. Currently the links go to a commons page https://aseees.hcommons.org/register/ where you get an error message "User registration is currently not allowed."

**Comment by mikethicke** [comment]
https://github.com/MESH-Research/hc-custom/commit/4034ffa1d27bb99680dd73ca09ff3075a09a31f7 Fixes the logic for Join Group buttons in the group listing page. Join Group button is not showing for non-members in the banner, which seems acceptable.

**Comment by adonlon** [comment]
I tested as a logged out user on the groups directory page and no longer saw the greyed out Join buttons, as expected. 

You may still be working on related issues, but I'll note them here:
There's still a message at the top of the Groups and Members directories, which I think previously were only visible for logged-in non-society members. 

The one on Groups could probably stay if the link were corrected (currently "Join MLA [or UP or MSU etc] now!" links to /register/ and the page says "User registration is currently not allowed"). (It should be corrected even if it's removed for logged-out visitors, since it'll display for logged-in non-society members.) 

The message on Members doesn't really work for a logged-out visitor. It says "Only MLA members can follow others from here. To follow these members, go to Humanities Commons."
