### ISSUE TITLE
Migrate sustaining from dev to prod

### ISSUE THREAD

**Issue by kfitz** [MESH-Research/commons#330]
sustaining.hcommons-dev.org needs to be migrated to sustaining.hcommons.org, replacing the existing content there. There are complexities involved in export from dev and import to prod, so Mike needs to do some pondering!

**Comment by mikethicke** [comment]
@kfitz Is the site ready to migrate?

**Comment by kfitz** [comment]
If you're happy with the tech pages, and @bjr70 is happy with the minutes for the advisory groups, we're good to go! Thanks, @mikethicke

**Comment by mikethicke** [comment]
Sustaining site moved to production.

Note: I moved the site by copying the upload directory and dumping the database tables directly. This seems to be the easiest way of transferring sites from dev to prod since the default importer can't download images from dev to prod. Have to be careful about table names though for new sites.
