### ISSUE TITLE
CORE deposits not rendering on front end

### ISSUE THREAD

**Issue by katknow** [MESH-Research/commons#363]
Reported: 5/12/2022
Site: Humanities Commons
Area: CORE

During @katknow's clearing of pending CORE deposits, she discovered that some CORE deposits are not rendering on the front end but are definitely fully there on the back end. Both of these examples are pending review:

Amanda Kane Rooks, "Maternal Eroticism and Female Desire in Sue Miller’s The Good Mother"
back end: https://hcommons.org/wp-admin/post.php?post=32470&action=edit
front end: https://hcommons.org/deposits/item/hc:30513/

Franco Zappettini, "The Brexit referendum: how trade and immigration in the discourses of the official campaigns have legitimised a toxic (inter)national logic"
back end: https://hcommons.org/wp-admin/post.php?post=32584&action=edit
front end: https://hcommons.org/deposits/item/hc:30583/

On 5/12/2022, user Ben Newbound emailed saying that one of his published deposits has disappeared, and it seems to be the same issue. Unlike the above examples, this deposit was in published status:

back end: https://hcommons.org/wp-admin/post.php?post=37607&action=edit
front end: https://hcommons.org/deposits/item/hc:32667/

The only similarity I can see across deposits is all are from 2020.

**Comment by ericknappe** [comment]
[hc:30513/](https://hcommons.org/deposits/item/hc:30513/)
[hc:30583/](https://hcommons.org/deposits/item/hc:30583/)

Solr document was missing for these deposit. Since they had prior downloads, I'd say this might have been a problem prior or at the migration .

Since the only thing missing was the Solr document I resolved these by saving in WP admin. 

[hc:32667/](https://hcommons.org/deposits/item/hc:32667/) appears fin to me. No problem downloading and the deposit check utility reports no errors.
