### ISSUE TITLE
Registration on societies results in blank page on redirect

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#398]
When registering on mla.hcommons-dev.org both hctester10 and hctester50 were returned to a blank page on successful registration. I had to clear cookies to log in as both users. I then expunged both users to try on HC vs. MLA.

When trying to register hctester50 through humanities commons it returned a message stating that the user was already member and set that attempt to the status "duplicate" when trying to set up a Google authentication. I can't find another user with that email address. I have seen this happen with users stuck in the LDAP, but the users used only Google auth, not an HCID. Have also seen stuck organizational identity records. 

Was not able to replicate the duplicate error with HCTester10, and did not receive a blank screen when registering hctester10 on Humanities Commons. Once registered hctester10 was able to visit all of the Commons they are a member of and  an issue with society roles.

**Comment by mikethicke** [comment]
This was an order of operations issue. When a user logs in, a number of things have to happen:

1) The user needs to be authenticated
2) BuddyPress needs to initialize
3) The user needs to have their memberships sync'd from COmanage / their SAML session

Previously, the order of these operations was 1-3-2, which caused problems because adding members to groups in 3 depends on BuddyPress to be initialized (2). To get around this requirement, (3) had been written using direct database calls, but that made it slow and it was still partially dependent on BuddyPress, causing it to fail in some circumstances.

The initial fix (https://github.com/MESH-Research/humanities-commons/commit/a9c487195bf2cc6a8bff2829cb032e35576634aa) made the order 2-1-3, which meant that BuddyPress failed to initialize correctly, eventually resulting in PHP crashing with an out-of-memory error further down the line.

The revised fix (makes the order 1-2-3 by changing the action hook for  hc-simplesaml.php::hcommons_set_user_member_types( https://github.com/MESH-Research/humanities-commons/commit/284b98c661f8d631428ffcf9233b7ae97f2fa5ca) from 'wp_saml_auth_existing_user_authenticated' to 'bp_init' with a late priority to ensure that it fires after BuddyPress has initialized.

The commits also include refactoring and code cleaning.
