### ISSUE TITLE
Odd issue with follow and group functionality in WP6

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#402]
When following a member from the Members page or from a profile the request never completes (it keeps circling) but if you refresh the page it has worked. I've seen a similar issue with groups buttons, but the groups seem to work intermittently.

**Comment by bjr70** [comment]
I can replicate this in multiple browsers with a test user, but not with an admin user. Admin users experience the expected result.

**Comment by babaklar** [comment]
I'm experiencing a similar issue to this when requesting group membership to a private group. When I click the "request membership" button, nothing happens, and when I refresh the page it shows the request was sent. However, in my group admin account, I never received any membership requests.

Shortly after, in the group, I started having issues with the "as the only admin, you cannot leave the group" error message. Not sure if these are related? ![Screen Shot 2022-06-30 at 2.22.02 PM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/3a0ca30b-0f79-49c8-8d12-a7451587ce2b)

**Comment by bjr70** [comment]
I got another weird popup just clicking on groups in the sidebar after logging in Something funky is going on with this page I think. Javascript issue? ![random popup.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/cef6fb0a-37b6-40fd-95d3-585736cb54c0)

**Comment by bjr70** [comment]
Now that I think about it I left a group yesterday. Could this be the delayed popup thing we saw previously that KF mentioned in chat?

**Comment by bjr70** [comment]
Every time I log in as myself (bonnie) I get this popup when I click on the groups link in the left-hand sidebar: ![adminpopup.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/61fd9df8-104d-4f03-9f7d-1392b9f9f31b)

**Comment by bjr70** [comment]
I am also able to replicate Larissa's issue above where I requested membership in Dave's Test Group 2 as myself. The request membership button disappeared, but the request never made it to Dave. It's gone in the ether.

**Comment by mikethicke** [comment]
I think there are two underlying issues here.

## Issue #1 - A user can remain logged-in to WordPress after their SAML session is expired. 

When the page reloads, they will be removed from all groups and societies because the membership data that is expected to be passed to WordPress from the SAML session is not present. This commit makes it so that if there is no membership data available, leave a user's memberships unchanged. A possible problem with this is if a user never logs out, they could remain in societies / groups they have been removed from. I'm not sure how long a user is able to remain logged-in to WordPress.

https://github.com/MESH-Research/humanities-commons/commit/d5047b29ea1249cf2e5e549277f92fd04e72efc8

## Issue #2 - A bug in the buddypress-followers plugin

When a user is follower or unfollowed, the buddyprss-followers plugin generates an email notification. There is a bug in that function where a string value is treated as an array:

```php
function bp_follow_new_follow_email_notification( $args = '' ) {
	...

	// Check to see if this leader has already been notified of this follower before
	$has_notified = bp_get_user_meta( $r['follower_id'], 'bp_follow_has_notified', true );

	...

	// Not been notified before, update usermeta and continue to mail
	$has_notified[] = $r['leader_id'];
	
         ...
```

In the above snippet, ```$has_notified``` is returned as a single value rather than an array, because the third parameter in the function call is set to ```true``` rather than ```false``` (see: https://www.buddyboss.com/resources/reference/functions/bp_get_user_meta/ ). It is then treated as an array below, which causes an exception to be thrown and the AJAX call returns an error so the Follow button never leaves the spinning state even though the user was followed. Setting the third parameter to ```false``` so that ```$has_notified``` is an array seems to fix the problem.

I think this is a PHP compatibility issue rather than a WordPress 6.0 issue. We recently updated to PHP 7.4.

The buddypress-followers plugin has not been updated in 6 years ( https://wordpress.org/plugins/buddypress-followers/ ). I don't think we can abandon it easily, however, as it is part of our core functionality.

For now, I think this means we have to fork the plugin. 🤮

**Comment by mikethicke** [comment]
The buddypress-followers plugin has a newer version on its GitHub page ( https://github.com/r-a-y/buddypress-followers ) than is available on the wordpress.org plugin repository. The newer version corrects the above bug. Switching to that addresses the issue.

This commit removes a now-redundant spinning animation created by BuddyBoss. The plugin now creates this animation so BuddyBoss was causing there to be two spinners.  https://github.com/MESH-Research/boss-child/commit/5d757ba8511f55df251cdb63811b48673076f6ea

**Comment by mikethicke** [comment]
There is a handler that is supposed to force-reload the page when you join / leave a group ( https://github.com/MESH-Research/boss-child/blob/7107b5288cc0b317332aff2e783f2e6a8f363400/js/boss-child.js#L1 ). Because the live() function was deprecated (https://api.jquery.com/live/) the handler wasn't being called, so the page wasn't force-reloaded and the user didn't immediately see the notification. 

This commit addresses that issue: https://github.com/MESH-Research/boss-child/commit/7107b5288cc0b317332aff2e783f2e6a8f363400 

The resulting user experience is, imo, pretty terrible, but I think it is operating as designed.
