### ISSUE TITLE
Email to users about Twitter login removal plans

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#489]
Create an email to alert users that use only Twitter to log in that they should add another login method.

**Comment by rekmla** [comment]
Updated [spreadsheet](https://docs.google.com/spreadsheets/d/12g6f3VV-wcUrU4sH1leVpcBTXktLGa95fc3jhcDaWTY/edit?usp=sharingl)  after twitter enrollment cutoff sorted by Shib Login Methods and last activity.

I think Shib Login Methods is best for identifying twitter only WP users. I've added our user meta about opting out of communications, but I think this supersedes that setting.

I've added SAML Login Methods which is more accurate after the migration to simplesamlphp and satosa, but I think you can safely filter by Shib Login Methods with one exception. MLA Commons users that have Twitter and Legacy MLA but have only used Twitter since the simplesamlphp cutover might effectively be Twitter only users if their MLA membership has expired.

Blank SAML Login Methods are people that have not been on the system in a long time.

**Comment by bjr70** [comment]
Updated user list: https://docs.google.com/spreadsheets/d/12g6f3VV-wcUrU4sH1leVpcBTXktLGa95fc3jhcDaWTY/edit#gid=0
